name: Run Integration Tests
description: Run the development server, and run integration tests.

runs:
  using: "composite"

  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Restore node_modules cache
      uses: actions/cache@v4
      with:
        path: client/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('client/yarn.lock') }}

    - name: Install Playwright
      working-directory: client
      run: yarn playwright install
      shell: bash

    - name: Run server
      working-directory: client
      run: yarn dev &
      shell: bash

    - name: Wait for server to be ready
      run: sleep 10
      shell: bash

    - name: Run integration tests
      working-directory: client
      run: yarn integration
      shell: bash
