name: Lint Code
description: Set up Node.js and run the linter.

runs:
  using: "composite"

  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Restore node_modules cache
      uses: actions/cache@v4
      with:
        path: client/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('client/yarn.lock') }}

    - name: Run linter
      working-directory: client
      run: yarn lint
      shell: bash