name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and Test
        uses: ./.github/actions/api/test

  deploy-api-dev:
    needs: build-and-test-api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to Heroku
        uses: ./.github/actions/api/deploy
        with:
          heroku-app-name: ${{ secrets.HEROKU_APP_NAME }}
          heroku-api-key: ${{ secrets.HEROKU_API_KEY }}

  install-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Node.js Dependencies
        uses: ./.github/actions/client/install
        id: install-node

  lint-client:
    needs: install-client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Lint Code
        uses: ./.github/actions/client/lint

  build-client:
    needs: install-client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build App
        uses: ./.github/actions/client/build
        with:
          mode: production

  typecheck-client:
    needs: install-client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Type Check
        uses: ./.github/actions/client/type-check

  test-client:
    needs: install-client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Tests
        uses: ./.github/actions/client/test

  integration-test-client:
    needs: install-client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Integration Tests
        uses: ./.github/actions/client/integration-test

  deploy-client-dev:
    needs: [build-client, lint-client, typecheck-client, test-client, integration-test-client, deploy-api-dev]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Render
      uses: ./.github/actions/client/deploy
      with:
        render-api-key: ${{ secrets.RENDER_API_KEY }}
        service-id: srv-crbkoobv2p9s73di6650

  e2e-test:
    needs: [deploy-api-dev, deploy-client-dev]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run E2E Tests
        uses: ./.github/actions/e2e
  
  deploy-api-prod:
    needs: [e2e-test]
    runs-on: ubuntu-latest

    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to Heroku
        uses: ./.github/actions/api/deploy
        with:
          heroku-app-name: ${{ secrets.HEROKU_APP_NAME_PROD }}
          heroku-api-key: ${{ secrets.HEROKU_API_KEY }}

  deploy-client-prod:
    needs: [e2e-test, deploy-api-prod]
    runs-on: ubuntu-latest

    environment: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Render
      uses: ./.github/actions/client/deploy
      with:
        render-api-key: ${{ secrets.RENDER_API_KEY }}
        service-id: srv-cqrnuuogph6c73a2lph0

