name: Deploy Client Dev

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Node.js Dependencies
        uses: ./.github/actions/client/install
        id: install-node

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Lint Code
        uses: ./.github/actions/client/lint

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build App
        uses: ./.github/actions/client/build
        with:
          mode: development

  typecheck:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Type Check
        uses: ./.github/actions/client/type-check

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Tests
        uses: ./.github/actions/client/test

  integration-test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Integration Tests
        uses: ./.github/actions/client/integration-test

  deploy:
    needs: [build, lint, typecheck, test, integration-test]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Render
      uses: ./.github/actions/client/deploy
      with:
        render-api-key: ${{ secrets.RENDER_API_KEY }}
        service-id: srv-crbkoobv2p9s73di6650
